import 'package:flutter/material.dart';

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Container(
        color: Colors.white,
        child: ListView(
          children: [
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle:
                  Text("A sufficiently long subtitle warrants three lines."),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
            ListTile(
              focusColor: Colors.amber,
              hoverColor: Colors.black,
              selectedTileColor: Colors.red,
              leading: Icon(Icons.ac_unit),
              tileColor: Colors.amber,
              subtitle: Text("Blow"),
              onTap: () {},
              trailing: Icon(Icons.ac_unit_outlined),
              dense: true,
              selected: true,
              isThreeLine: true,
              title: Text("Whistle"),
            ),
          ],
        ));
  }
}
